using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Text;
using Backend;
using UnityEngine;

#nullable enable

public class GameFrontend : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        try
        {
            //var header = new RpcHeader();
            //header.body_size = 10;
            //header.rpc = "waddup";
            //header.is_return = false;
            //Debug.Log(JsonUtility.ToJson(header));
            //Debug.Log(BuiltinUtils.JsonSerialize(header));


            var server = new IPEndPoint(IPAddress.Loopback, 11111);
            UdpClient udpClient = new UdpClient(server);
            var peer = new IPEndPoint(IPAddress.Loopback, 34567);
            udpClient.Connect(peer);
            var chan = new UDPChannel(udpClient, peer);

            //Backend.Service.HandleOne(chan, new Handler());


            var client = new Backend.ServiceClient(chan);
            var msg = new ExampleMessage();
            msg.msg = "hello!";
            var res = client.call_example_message(msg);
            Debug.Assert(res.msg == "world!");

        }
        catch (Exception e)
        {
            Console.WriteLine(e.ToString());
        }
    }

    // Update is called once per frame
    void Update()
    {

    }

    private class Handler : Backend.RpcHandler
    {
        public ExampleReturn HandleExampleMessage(ExampleMessage msg)
        {
            Debug.Assert(msg.msg == "hello!");
            var ret = new ExampleReturn();
            ret.msg = "world!";
            return ret;
        }
    }
}

public class UDPChannel : IChannel
{
    private UdpClient client;
    private IPEndPoint peer;

    public UDPChannel(UdpClient client)
    {
        this.client = client;
    }
    public UDPChannel(UdpClient client, IPEndPoint peer)
    {
        this.client = client;
        this.peer = peer;
    }
    public byte[] recv()
    {
        IPEndPoint? endpoint = peer;
        return client.Receive(ref endpoint);
    }

    public void send(byte[] bytes)
    {
        client.Send(bytes, bytes.Length);
    }
}



// Below is autogenerated

public class BuiltinUtils
{
    public static byte[] JsonSerialize<T>(T obj)
    {
        return Encoding.UTF8.GetBytes(JsonUtility.ToJson(obj));
    }
    public static T? JsonDeserialize<T>(byte[] bytes)
    {
        var s = Encoding.ASCII.GetString(bytes);
        return JsonUtility.FromJson<T>(s);
    }

    public static int? SerializeJsonInto<T>(T obj, byte[] bytes)
    {
        var b = BuiltinUtils.JsonSerialize(obj);
        if (b.Length > bytes.Length)
        {
            return null;
        }
        b.ToArray().CopyTo(bytes, 0);
        return b.Length;
    }

    public static int? findStructJsonBounds(byte[] bytes)
    {
        System.Collections.IEnumerator iter = bytes.GetEnumerator();
        if (!iter.MoveNext())
        {
            return null;
        }
        if ((byte)iter.Current != '{')
        {
            return null;
        }
        var count = 1;
        var indent = 1;
        while (iter.MoveNext())
        {
            count += 1;
            // TODO/FIXME: Need to support detecting if inside a string.
            if ((byte)iter.Current == '{')
            {
                indent += 1;
            }
            if ((byte)iter.Current == '}')
            {
                indent -= 1;
                if (indent == 0)
                {
                    return count;
                }
            }
        }
        return null;
    }


}

[Serializable]
public class RpcHeader
{
    public string rpc; //{ get; set; }
    public int body_size; //{ get; set; }
    public bool is_return;//{ get; set; }
}
public interface IChannel {
    void send(byte[] bytes);
    byte[] recv();
}



/// For example:
/// message ExampleMessage {
///     msg: string,
/// }
/// message ExampleReturn {
///     msg: string,
/// }
/// service Backend {
///     rpc ExampleMessage(ExampleMessage)
/// }

[Serializable]
public class ExampleMessage
{
    public String msg;// { get; set; }
}

[Serializable]
public class ExampleReturn
{
    public String msg;// { get; set; }
}

namespace Backend {

public interface RpcArgVariant {}
public interface RpcRetVariant {}

public class ExampleRpcArg : RpcArgVariant {
    public ExampleMessage Data {get; set;}
    public ExampleRpcArg(ExampleMessage data)
    {
        Data = data;
}
}
public class ExampleRpcRet : RpcRetVariant {
    public ExampleReturn Data { get; set;}
        public ExampleRpcRet(ExampleReturn data) {
            Data = data;
        }
}

public class Serializer {
        const string EXAMPLE_RPC_ID = "ExampleRpc";

        public static (RpcArgVariant?, int) ParseRpcRecv(byte[] bytes) {
            (RpcArgVariant?, int) fail = (null, 0);

            // Parse header
            var bound = BuiltinUtils.findStructJsonBounds(bytes);
            if (bound == null)
            {
                return fail;
            }
            var header = BuiltinUtils.JsonDeserialize<RpcHeader>(bytes[..bound.Value]);
            if (header == null)
                return fail;

            // Parse body
            var start = bound.Value;
            var end = start + (int)header.body_size;
            switch (header.rpc) {
                case EXAMPLE_RPC_ID:
                    var ret = BuiltinUtils.JsonDeserialize<ExampleMessage>(bytes[start..end]);
                    if (ret == null)
                        return fail;
                    return (new ExampleRpcArg(ret), end);
                default:
                    return fail;
            }
    }
        public static (RpcRetVariant?, int) ParseRpcResult(byte[] bytes)
        {
            (RpcRetVariant?, int) fail = (null, 0);

            // Parse header
            var bound = BuiltinUtils.findStructJsonBounds(bytes);
            if (bound == null)
            {
                return fail;
            }
            var header = BuiltinUtils.JsonDeserialize<RpcHeader>(bytes[..bound.Value]);
            if (header == null)
                return fail;

            // Parse body
            var start = bound.Value;
            var end = start + (int)header.body_size;
            switch (header.rpc)
            {
                case EXAMPLE_RPC_ID:
                    var ret = BuiltinUtils.JsonDeserialize<ExampleReturn>(bytes[start..end]);
                    if (ret == null)
                        return fail;
                    return (new ExampleRpcRet(ret), end);
                default:
                    throw new Exception("Unhandle case");
            }
        }

        public static byte[] SerializeRpcArg(RpcArgVariant arg) {
            // Create header
            var header = new RpcHeader();
            header.is_return = false;
            // Create body
            byte[] body;
            switch (arg) {
                case ExampleRpcArg targ:
                    body = BuiltinUtils.JsonSerialize(targ.Data);
                    header.rpc = EXAMPLE_RPC_ID;
                    break;
                default:
                    throw new Exception("Unhandle case");
            }
            // Finalize Header
            header.body_size = body.Length;
            var serialHeader = BuiltinUtils.JsonSerialize(header);
            // Stuff together into bytes
            byte[] ret = new byte[serialHeader.Length + body.Length];
            System.Array.Copy(serialHeader, ret, serialHeader.Length);
            System.Array.Copy(body, 0, ret, serialHeader.Length, body.Length);
            return ret;
        }

        public static byte[] SerializeRpcRet(RpcRetVariant arg)
        {
            // Create header
            var header = new RpcHeader();
            header.is_return = true;
            // Create body
            byte[] body;
            switch (arg)
            {
                case ExampleRpcRet targ:
                    body = BuiltinUtils.JsonSerialize(targ.Data);
                    header.rpc = EXAMPLE_RPC_ID;
                    break;
                default:
                    throw new Exception("Unhandle case");
            }
            // Finalize Header
            header.body_size = body.Length;
            var serialHeader = BuiltinUtils.JsonSerialize(header);
            // Stuff together into bytes
            byte[] ret = new byte[serialHeader.Length + body.Length];
            System.Array.Copy(serialHeader, ret, serialHeader.Length);
            System.Array.Copy(body,0, ret, serialHeader.Length, body.Length);
            return ret;
        }
    }



    // User Interfaces
    public interface RpcHandler
    {
        ExampleReturn HandleExampleMessage(ExampleMessage msg);
        RpcRetVariant HandleRpcReceived(RpcArgVariant arg)
        {
            switch (arg)
            {
                case ExampleRpcArg arg1:
                    var res = HandleExampleMessage(arg1.Data);
                    return new ExampleRpcRet(res);
                default:
                    // All variants should be supported through autogeneration
                    throw new Exception("Unreachable case??");
            }
        }
    }

    public class Service {
        public static void HandleOne(IChannel chan, RpcHandler handler) {
            byte[] bytes = chan.recv();
            var start = 0;
            while (true)
            {
                // Parse the RPC
                (RpcArgVariant? arg, int amt) = Serializer.ParseRpcRecv(bytes[start..]);
                if (arg == null) break;
                // Handle the RPC
                var res = handler.HandleRpcReceived(arg);
                // Push the result
                chan.send(Serializer.SerializeRpcRet(res));

            }
        }
        public static void HandleLoop(IChannel chan, RpcHandler handler) {
            while (true)
            {
                HandleOne(chan, handler);
            }
        }
    }

    public class ServiceClient {
        private IChannel chan;
        public ServiceClient(IChannel chan) {
            this.chan = chan;
        }

        public RpcRetVariant call(RpcArgVariant arg) {
            this.chan.send(Serializer.SerializeRpcArg(arg));
            var bytes = this.chan.recv();
            var (res, amt) = Serializer.ParseRpcResult(bytes);
            // TODO(error_hadnling)
            if (res == null) throw new Exception("No result recvd");
            return res;
        }

        public ExampleReturn call_example_message(ExampleMessage arg) {
            var res = (ExampleRpcRet)this.call(new ExampleRpcArg(arg));
            return res.Data;
        }
    }
}

